#spring:
#  profiles:
#    active: dev # 开发环境
#    active: test # 测试环境
#    active: info # 开发环境

#server:
#  port: 10001
#
#spring:
#  application:
#    name: mall-coupon
#
###nacos 配置
#  cloud:
#    nacos:
#      discovery: #Nacos注册中心地址
#        server-addr: localhost:8848
#
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/mall_sms?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
#    driver-class-name: com.mysql.jdbc.Driver
#
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#
#logging:
#  level:
#    com.xp.mall: debug


###该配置文件 已经放到了nacos配置中心


